project:
  type: book

book:
  title: "Flow mapping with Arabesque 2"
  author: "Françoise Bahoken"
  date: "27/05/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - 01-interface.qmd
    - 02-data-import.qmd
    - 03-data-pre-processing.qmd
    - 04-geographical-layers.qmd
    - 05-design-of-the-flowmap.qmd
    - 06-filtering-flowdata.qmd
    - 07-flowmap-cosmetics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    embed-resources: true
  pdf:
    documentclass: scrreprt

editor: visual

epub:
    cover-image: cover-image.png

