project:
  type: book

book:
  title: "Flow mapping with Arabesque 2"
  author: "Françoise Bahoken"
  date: "16/05/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - 01-interface.qmd
    - 02-data-import.qmd
    - 03-data-pre-processing.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    embed-resources: true
  pdf:
    documentclass: scrreprt

editor: visual

epub:
    cover-image: arabesque_cover.png

